import git
import os

readme = """
# %s

%s

---

This project was created using [MicroSprintLab](https://github.com/MicahWade/MicroSprintLab).

⏱️ **Sprint completed in %ss.**

---

- Installation steps
%s

---

- Reflection and post-sprint notes
%s

---

Auto-generated by MicroSprintLab

"""


def FinishProject(
    title: str, description: str, path, projectPath, time: int, remote: bool
):
    mainRepo = FirstSetup(projectPath)
    print("Please add Install Instruction")
    instruction = input().strip() or " "
    print("Please add Reflections")
    reflection = input().strip() or " "
    with open(os.path.join(path, "readme.md"), "w") as file:
        file.write(readme % (title, description, time, instruction, reflection))
    with open(os.path.join(projectPath, "readme.md"), "a") as file:
        file.write(title)
    mainRepo.index.commit(title)
    if remote:
        try:
            origin = mainRepo.remote(name="origin")
            origin.push()
        except:
            print("Unable to push to remote")


def FirstSetup(projectPath):
    try:
        repo = git.Repo(projectPath)
    except (git.InvalidGitRepositoryError, git.NoSuchPathError):
        repo = git.Repo.init(projectPath)
    repo.git.add(all=True)
    return repo
